apiVersion: v1
data:
  haproxy.cfg: |
    defaults REDIS
    mode tcp
    timeout connect 3s
    timeout server 6s
    timeout client 6s

    frontend ft_redis
    bind *:6379 name redis
    default_backend bk_redis

    backend bk_redis
    option tcp-check
    tcp-check connect
    tcp-check send AUTH\ redispassword\r\n
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send info\ replication\r\n
    tcp-check expect string role:master
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    server redis_1 passbolt-redis-node-0.passbolt-redis-headless:6379 check inter 1s
    server redis_2 passbolt-redis-node-1.passbolt-redis-headless:6379 check inter 1s
    server redis_3 passbolt-redis-node-2.passbolt-redis-headless:6379 check inter 1s
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-09-09T18:33:04Z"
  labels:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.5.3
  name: haproxy
  namespace: default
  resourceVersion: "845251"
  uid: 3531e65e-9959-4596-b6d7-bef06f343251
