dependencies:
#  - name: mysql
#    version: 6.4
#    repository: https://charts.bitnami.com/bitnami
  - name: percona
    version: 1.2
    repository: https://kubernetes-charts.storage.googleapis.com/