apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passbolt-helm.fullname" . }}-config
data:
  passbolt.conf: |
    [www]
    pm = dynamic
    pm.max_children = 40
    pm.start_servers = 16
    pm.min_spare_servers = 8
    pm.max_spare_servers = 24
    clear_env = no
    php_value[memory_limit] = 512M
    php_value[post_max_size] = 24M
    php_value[upload_max_filesize] = 24M
    php_admin_value[max_execution_time] = 300
    php_admin_value[session.gc_maxlifetime] = {{ .Values.passbolt.config.php.session.lifetime }}
    {{- if .Values.passbolt.config.php.session.redis.enabled }}
    {{- if .Values.redis.enabled }}
    php_admin_value[session.save_handler] = redis
    php_admin_value[session.save_path] = "tcp://{{ .Values.passbolt.config.php.session.redis.service }}:6379?auth={{ .Values.redis.auth.password }}"
    {{- else if index .Values "redis-cluster" "enabled" }}
    php_admin_value[session.save_handler] = rediscluster
    php_admin_value[session.save_path] = "seed[]={{ .Values.passbolt.config.php.session.redis.service }}:6379&auth={{ index .Values "redis-cluster" "password" }}&failover=error&timeout=2&read_timeout=2&persistent=1"
    {{- end }}
    {{- end }}
