apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passbolt-helm.fullname" . }}-gpg
  labels:
{{ include "passbolt-helm.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  "serverkey.asc": {{ .Files.Get "secrets/gpg/serverkey.asc" | b64enc | quote }}
  "serverkey_private.asc": {{ .Files.Get "secrets/gpg/serverkey_rivate.asc" | b64enc | quote }}